### ISSUE TITLE
'The IPython Notebook.ipynb': invisible scatterplots

### ISSUE THREAD

**Issue by akkana** [PacktPublishing/Python-Data-Science-Essentials-Second-Edition#1]
In 'The IPython Notebook.ipynb', in In[25], it does:
    plt.scatter(X, Y, s=32, marker='o', facecolors='white')
At least in Python 3.6.4 on Debian, this produces an invisible plot, because the circles have white interiors and white boundaries. I had to do this to get them to look like the preview:
    plt.scatter(X, Y, s=32, marker='o', edgecolors='black', facecolors='white')

Also, in 35, "FutureWarning: pandas.scatter_matrix is deprecated. Use pandas.plotting.scatter_matrix instead".

**Comment by sohamapackt** [comment]
Hi,

I am closing this issue. If the issue still persists, feel free to reopen it.
Thanks!
