### ISSUE TITLE
Documenting Notebooks

### ISSUE THREAD

**Issue by shivamsingh17** [PacktPublishing/Python-Data-Science-Essentials-Second-Edition#2]
I wish to become a contributor by adding documentation to cells of notebook to make them more understandable . I am certified in deep learning by Microsoft.
https://courses.edx.org/certificates/65d6d45a32754bbb947894800cdf998c

**Comment by techsachinkumar** [comment]
Hi @shivamsingh17 

Could you be more specific in terms "become a contributor by adding documentation to cells of notebook"?
Do you want to contribute to this specific book or do you want to become a reviewer for Packt books.

Regards.

**Comment by shivamsingh17** [comment]
Technically , I can provide notebooks and review books on deep learning. I
have read most of the books of machine learning and deep learning by
packt.i think they can be made even more interactive and content need to be
standardized.

**Comment by techsachinkumar** [comment]
Thanks for your concern.

Could you provide me with your profile and pages of work if any, so i can provide it to the concerned team.
Likewise you would be contacted by our team for books on machine learning and deep learning.

Regards.

**Comment by shivamsingh17** [comment]
I cannot share my work on GitHub abiding honor code.Henceforth, I will send
you a drobbox link of my works.Currently , I have completed A project on
lung cancer detection system using CNN.

**Comment by techsachinkumar** [comment]
Okay @shivamsingh17 

Please share your LinkedIn profile with us.

You can contact me at:
Email - sachinkumar@packtpub.com
Skype - packt.sachinkumar

Forward me those links and i would forward it to the concerned team so that they can get in touch with you.

Regards.
